# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: npm_publish

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  publish:
    name: "npm-publish: deskor-plugin-preload"
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged && github.head_ref == 'package/deskor-plugin-preload' }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: npm publish
        run: |
          cd ./packages/deskor-plugin-preload/
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: auto taging
        uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          tag_prefix: "plugin/preload-v"
          package_root: "./packages/deskor-plugin-preload"
